export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const GET_ASSESSMENTS_REQUEST = 'GET_ASSESSMENTS_REQUEST';
export const GET_GROUPS_REQUEST = 'GET_GROUPS_REQUEST';
